name: CI/CD Pipeline

on: #Every time you push code to main, the pipeline starts automatically.
  push:
    branches: [ "main" ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  AWS_REGION: us-east-1
  ECR_REPOSITORY: todo-backend
  ECS_CLUSTER: todo-cluster
  ECS_SERVICE: todo-service
jobs:
  build-and-scan:
    runs-on: ubuntu-latest #Creates a virtual machine (Linux) to run your pipeline.

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 #Downloads your repo into the runner.

    - name: Build Docker image
      run: docker build -t todo-backend:latest ./backend #Builds your backend into a Docker image.

    - name: Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'todo-backend:latest'
        format: 'table'
        severity: 'CRITICAL,HIGH'
  deploy:
    needs: build-and-scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 🔐 connect to AWS
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 🐳 login to ECR
    - name: Login to ECR
      run: |
        $password = aws ecr get-login-password --region us-east-1
        docker login --username AWS --password $password $(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_REGION.amazonaws.com

    # 🏷️ tag image
    - name: Tag image
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        docker tag todo-backend:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

    # 📤 push image
    - name: Push image
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

    # 🚀 deploy to ECS
    - name: Force new deployment
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment